blank_issues_enabled: false
contact_links:
  - name: Live Chat (on Discord)
    url: https://discord.gg/rNpQgYn
    about: Live support for MassTransit
  - name: GitHub Discussions
    url: https://github.com/MassTransit/MassTransit/discussions
    about: Submit questions, ideas, or general conversation topics